version: '3'
services:

  apache-cassandra:
    image: 'cassandra'
    container_name: 'apache-cassandra-test'
    networks:
      - backend
    healthcheck:
      test: cqlsh
      interval: 60s
      retries: 5
      timeout: 10s

  group-service:
    image: 'denpool/group-service:version1'
    ports:
      - "9000:9000"
    restart: always
    networks:
      - backend
    depends_on:
      apache-cassandra:
        condition: service_healthy

networks:
  backend:
    driver: bridge